name: netease_meeting_assets
description: A Flutter package which contains related assets used by NEMeeting, such as images, icon fonts.
version: 0.1.0
homepage: https://yunxin.163.com/
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
