arb-dir: lib/l10n
output-dir: lib/src/meeting_localization
template-arb-file: strings_zh.arb
output-localization-file: meeting_ui_kit_localizations.dart
output-class: NEMeetingUIKitLocalizations
header-file: header.txt
synthetic-package: false
untranslated-messages-file: untranslated.txt
format: true