name: netease_meeting_core
description: A package provide related APIs to start、schedule、join meeting.
version: 0.1.0-rc.0
homepage: https://yunxin.163.com/
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.6
  async: 2.11.0
  shared_preferences: 2.0.15
  dio: ^4.0.6

  path_provider: 2.0.11
  uuid: ^4.3.3
  device_info_plus: ^8.0.0

  yunxin_alog: ^2.0.0
  netease_roomkit: 1.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
