repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!((bugfix|feature|release|hotfix|support|ci)\/[A-Za-z0-9\_\-\.]+)$|develop).*']
    -   id: check-case-conflict

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
    -   id: clang-format
        args: [--style=File, -i]
